### ISSUE TITLE
Duplicate class 

### ISSUE THREAD

**Issue by Demetresko** [infobip/mobile-messaging-sdk-huawei#1]
Hello, I am trying to integrate huawei infobip message service with standard infobip message service for android. When I try to build my project i get the error: 

       Duplicate class org.infobip.mobile.messaging.view.WebViewActivity$1 found in modules jetified-infobip-mobile-messaging-android-sdk-5.3.6-runtime (com.infobip:infobip-mobile-messaging-android-sdk:5.3.6) and jetified-infobip-mobile-messaging-huawei-sdk-2.2.3-runtime (com.infobip:infobip-mobile-messaging-huawei-sdk:2.2.3)

My app gradle looks like this:

 andImplementation ('com.infobip:infobip-mobile-messaging-android-sdk:5.3.6@aar') {
        transitive = true
    }

 hmsImplementation ('com.infobip:infobip-mobile-messaging-huawei-sdk:2.2.3@aar') {
        transitive = true
    }

Can you give me any idea how to fix this ?

**Comment by kostap13** [comment]
Hi @Demetresko 
Seems that you have included both android-sdk and huawei-sdk .
Could you please re-check yours config or provide more info?

Best regards

**Comment by Demetresko** [comment]
Yes, I did. Is there any way to work with both dependencies in one project ?

**Comment by kostap13** [comment]
Try to configure build flavors. It should helps

**Comment by kostap13** [comment]
Hi @Demetresko 

Could you please tell me does this issue actual?

**Comment by Demetresko** [comment]
Hi, yes it is, I will post more details little bit later

**Comment by Demetresko** [comment]
Sorry , I mixed up questions, this issue is resolved , thank you.
