### ISSUE TITLE
infobip-mobile-messaging-huawei-geo-sdk is not compatible with Android 12 requirements

### ISSUE THREAD

**Issue by Abner97** [infobip/mobile-messaging-sdk-huawei#3]
You need to add android:exported to your receiver tags in AndroidManfest XML for your geo SDK

![image](https://user-images.githubusercontent.com/12854083/204049164-e9966557-8b78-4402-8e0d-5d94ea8e23f9.png)

**Comment by riskpp** [comment]
Hi @Abner97 , we have rc version released with support of the Android 12 - https://github.com/infobip/mobile-messaging-sdk-huawei/releases/tag/3.0.0-rc6

Check the migration guide - https://github.com/infobip/mobile-messaging-sdk-huawei/wiki/Migration-guide#migration-from-2x-to-3x

**Comment by tjuric** [comment]
Stable 3.0.0 version has been released https://github.com/infobip/mobile-messaging-sdk-huawei/releases/tag/3.0.0. Closing this issue.
