### ISSUE TITLE
Chat history is not saved for the user

### ISSUE THREAD

**Issue by Marieye** [infobip/mobile-messaging-sdk-huawei#4]
STR:

1. Start a conversation from a user 
2. Log in with the same credentials on another device
3. Check chat history
4. Send smth to the operator and check the chat history on another device

Actual result: in portal.infobip are created 2 different chats after these steps / chat history is not the same on the UI for the same user

**Comment by jakubdzubak1** [comment]
Hi @Marieye,

we will check it and let  you know. Thank you for report.

**Comment by Marieye** [comment]
We found a problem. There was expired key. So we continued the operation of the key, and now issue doesn't reproduce.

**Comment by jakubdzubak1** [comment]
Thank you for info, closing the issue.
